In [31]:
import numpy as np

print(np.array([1,2,3,4]).reshape(4,1))

np.dot(np.array([1,2,3,4]).reshape(4,1), np.array([2,3]).reshape(1,2))

[[1]
 [2]
 [3]
 [4]]


array([[ 2,  3],
       [ 4,  6],
       [ 6,  9],
       [ 8, 12]])

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# サンプルデータの作成
Lambda_x1 = 30
Lambda_x2 = 50
samples_x1 = 300
samples_x2 = 200
x1 = np.random.poisson(Lambda_x1, samples_x1)
x2 = np.random.poisson(Lambda_x2, samples_x2)

X = np.concatenate([x1, x2])


def log_sum_exp(X):
    max_x = np.max(X, axis = 1).reshape(-1, 1)
    return np.log(np.sum(np.exp(X - max_x), axis = 1).reshape(-1, 1)) + max_x

# サンプリング用のリストを用意
sample_s = []
sample_lambda = []
sample_pi = []


# 定数の設定(繰り返し数, サンプル数, クラスタ数)
MAXITER = 100
N = len(X)
K = 2

# パラメータ初期値

init_Gam_param_a = 1
init_Gam_param_b = 1
init_Dir_alpha = np.ones(K)

# λ, πの初期値設定
Lambda = np.ones(K)
Pi = np.ones(K)

# πの条件に従って正規化(各値を合計値で割る)
if np.sum(Pi) != 1:
    Pi = Pi / np.sum(Pi)
    
# MAXITERの数だけ繰り返しサンプリング

for i in range(MAXITER):
    
    # sのデータ下地を準備
    s = np.zeros((N, K))
    
    # sをサンプルするためにηを算出
    log_eta = np.dot(X.reshape(N, 1), np.log(Lambda.reshape(1, K))) - Lambda.reshape(1, K) + np.log(Pi.reshape(1, K))

    # ηを正規化(logsumexp使ってオーバーフロー・アンダーフロー防ぐ)
    logsumexp_eta = -1 * log_sum_exp(log_eta)
    eta = np.exp(log_eta + logsumexp_eta)


In [22]:
test = np.array([[10,10,1], [1,2,3]])
max_x = np.max(test, axis =1).reshape(-1, 1)

print(max_x)
print(test - max_x)
print(np.exp(test-max_x))
print(np.sum(np.exp(test-max_x), axis = 1))
print(np.log(np.sum(np.exp(test-max_x), axis = 1)))

log_sum_exp(np.array([[10,10,1], [1,2,3]]))

[[10]
 [ 3]]
[[ 0  0 -9]
 [-2 -1  0]]
[[1.00000000e+00 1.00000000e+00 1.23409804e-04]
 [1.35335283e-01 3.67879441e-01 1.00000000e+00]]
[2.00012341 1.50321472]
[0.69320888 0.40760596]


array([[10.69320888],
       [ 3.40760596]])